var cueUrl = "http://libx.cs.vt.edu/~frostyt/Cues/cues/";
var jqPluginUrl = "http://libx.cs.vt.edu/~frostyt/Cues/jqplugins/";

addCue( jqPluginUrl + "jqPluginBubble.js" );
addCue( jqPluginUrl + "jqPluginToggleFade.js" );
addCue( cueUrl + "agricola.js" );
addCue( cueUrl + "alibris.js" );
addCue( cueUrl + "amazon.js" );
addCue( cueUrl + "autolink.js" );
addCue( cueUrl + "barnesandnoble.js");
addCue( cueUrl + "booklistonline.js" );
addCue( cueUrl + "chapters.js" );
addCue( cueUrl + "ecampus.js" );
addCue( cueUrl + "globalbooksinprint.js" );
addCue( cueUrl + "google.js" );
addCue( cueUrl + "nytimes.js" );
addCue( cueUrl + "powells.js" );
addCue( cueUrl + "serialsolutions.js" );
addCue( cueUrl + "vtcatalog.js" );
addCue( cueUrl + "wam.js" );
addCue( cueUrl + "yahoo.js" );
addCue( cueUrl + "coins.js" );
addCue( cueUrl + "abebooks.js" );
addCue( cueUrl + "openurl.js" );
addCue( cueUrl + "alert.js" );
