#!/bin/sh

# JsUnit - a JUnit port for JavaScript
# Copyright (C) 1999,2000,2001,2002,2003,2006 Joerg Schaible
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if test -z $1 || test ! -d $1; then
    echo "Usage: genasp <targetroot>"
    exit 1
fi

genasp()
{
    mkdir -p $2/`dirname $1`
    echo -e "<%\n" > $2/`dirname $1`/`basename $1 .js`.inc
    cat $1 >> $2/`dirname $1`/`basename $1 .js`.inc
    echo -e "\n" >> $2/`dirname $1`/`basename $1 .js`.inc
    echo -n "%>" >> $2/`dirname $1`/`basename $1 .js`.inc
}

CWD=$PWD
JSUNIT_HOME=`dirname $0`/..

case $1 in
[a-zA-Z]:* | /*) TARGET=$1;;
*) TARGET=$PWD/$1;;
esac

cd $JSUNIT_HOME
for dir in lib samples tests; do
    rm -rf $TARGET/$dir
    for js in `find $dir -name "*.js" ! -path "*/CVS*" -prune`; do
        genasp $js $TARGET
    done
done

cd $CWD

unset CWD JSUNIT_HOME TARGET
